### ISSUE TITLE
bower-dependency-tree\src\cli.js:12 Unexpected token >

### ISSUE THREAD

**Issue by adamsiemion** [shyiko/bower-dependency-tree#1]
`bower-dependency-tree` seems to fail regardless whatever is passed as an argument:

```
$ bower-dependency-tree

C:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\bower-dependency-tree\src\cli.js:12
var sortByName = (arr) => stable(arr, (l, r) => l.name.localeCompare(r.name));
                        ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\bower-dependency-tree\node_modules\babel\node_modules\babel-core\lib\babel\api\register\node.js:177:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\bower-dependency-tree\bin\bower-dependency-tree:20:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by shyiko** [comment]
Fixed in (783d52915146b4427f48f12c7d119ae76b6dc02f) 0.1.1 (just published). Thanks a lot for reporting this.
