### ISSUE TITLE
 No version found that was able to satisfy ^0.13.2

### ISSUE THREAD

**Issue by mafulafunk** [shyiko/bower-dependency-tree#2]
Running plain bower-dependency-tree:

Error: No version found that was able to satisfy ^0.13.2
    at createError (/usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/util/createError.js:4:15)
    at /usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/core/resolvers/pluginResolverFactory.js:124:35
    at _fulfilled (/usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by shyiko** [comment]
@mafulafunk Could you please provide your `bower.json`? Just tested on Node.js 6.9.1 - everything seems to be fine.

**Comment by mafulafunk** [comment]
Hhhmmm... a little uncomfortable with sending the bower.json public.
Could we start with a public bower project. i.e. git@github.com:PolymerElements/iron-form.git

I fail to get it running there too.

A bare run of:
bower-dependency-tree

fails with different missing packages.

And even after running:

> npm install karma karma-browserify@^4.2.1 'mocha@*' karma-mocha@~0.2.0 yargs@~3.9.1 xyz@^0.5.0 'nodeunit@>0.0.0' nyc@^2.1.0 coveralls@~2.11.2 karma-firefox-launcher@^0.1.6

bower-dependency-tree complains:

[...]
info: Fetching "xyz#^0.5.0"
info: Fetching "yargs#~3.9.1"
info: Fetching "paper-styles=polymerelements/paper-styles#^1.0.4"
Error: Package xyz not found
    at createError (/usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/util/createError.js:4:15)
    at /usr/local/lib/node_modules/bower-dependency-tree/node_modules/bower/lib/core/resolverFactory.js:206:23
[...]

**Comment by armujahid** [comment]
I am also facing similar issue:
```
Error: Package karma-firefox-launcher not found
    at createError (D:\Appl\nodejs\node_modules\bower-dependency-tree\node_modul
es\bower\lib\util\createError.js:4:15)
```
![image](https://user-images.githubusercontent.com/3725386/39816822-cd69e996-53b5-11e8-9742-ad76930147a2.png)
