### ISSUE TITLE
Custom bower registry

### ISSUE THREAD

**Issue by Csini** [shyiko/bower-dependency-tree#4]
Hi!

Are you supporting, if in .bowerrc there is a list of custom registries?
https://bower.io/docs/config/

I got error at that dependencies (mycustom-library), which are only in the custom registry:

`C:\ent\>bower-dependency-tree
info: Fetching "jquery#^3.2.1"
info: Fetching "angular#^1.6.4"
info: Fetching "angular-route#1.6.*"
info: Fetching "rapjs#1.2.*"
info: Fetching "angular-sanitize#^1.6.4"
info: Fetching "angular-ui-router#^0.4.2"
info: Fetching "angular-bootstrap#^2.5.0"
info: Fetching "moment#^2.18.1"
info: Fetching "ngmap#^1.18.0"
info: Fetching "lodash#^4.17.4"
info: Fetching "angular-paginate-anything#^4.2.0"
info: Fetching "ng-formio#^2.15.6"
info: Fetching "bootswatch#^3.3.7"
info: Fetching "font-awesome#^4.7.0"
info: Fetching "ng-formio-helper#^1.2.0"
info: Fetching "ng-prettyjson#^0.2.1"
info: Fetching "cloud-utils#^0.2.0"
info: Fetching "angular-poller#^0.4.5"
info: Fetching "angular-resource#^1.6.4"
info: Fetching "AngularJS-Toaster#toaster#^2.1.0"
info: Fetching "mycustom-library#blabla#^0.0.1"
info: Fetching "angular-mocks#1.6.*"
Error: Package mycustom-library not found
    at createError (c:\ent\npm-repository\node_modules\bower-dependenc
y-tree\node_modules\bower\lib\util\createError.js:4:15)
    at c:\ent\npm-repository\node_modules\bower-dependency-tree\node_m
odules\bower\lib\core\resolverFactory.js:206:23
    at _fulfilled (c:\ent\npm-repository\node_modules\bower-dependency
-tree\node_modules\bower\lib\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (c:\ent\npm-repository\node_modules\b
ower-dependency-tree\node_modules\bower\lib\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (c:\ent\npm-repository\node_mod
ules\bower-dependency-tree\node_modules\bower\lib\node_modules\q\q.js:796:13)
    at c:\ent\npm-repository\node_modules\bower-dependency-tree\node_m
odules\bower\lib\node_modules\q\q.js:604:44
    at runSingle (c:\ent\npm-repository\node_modules\bower-dependency-
tree\node_modules\bower\lib\node_modules\q\q.js:137:13)
    at flush (c:\ent\npm-repository\node_modules\bower-dependency-tree
\node_modules\bower\lib\node_modules\q\q.js:125:13)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)`

**Comment by shyiko** [comment]
https://github.com/shyiko/bower-dependency-tree/issues/3#issuecomment-304049859
